import type { Category, FoodItem } from "../types";

export const categories: Category[] = ["All", "Kimbab", "Soup", "Noodle"];

export const menuItems: FoodItem[] = [
  {
    id: "1",
    title: "Classic Beef Kimbab",
    description: "Sesame rice roll with marinated beef, egg, spinach and pickled radish.",
    macroCategory: "food",
    category: "Kimbab",
    price: 12.5,
    prepTime: "8 min",
    mostOrdered: true,
  },
  {
    id: "2",
    title: "Spicy Tuna Kimbab",
    description: "Creamy tuna, gochujang mayo and crunchy cucumber.",
    macroCategory: "food",
    category: "Kimbab",
    price: 11.75,
    prepTime: "7 min",
    promo: true,
  },
  {
    id: "3",
    title: "Kimchi Jjigae",
    description: "Deep kimchi stew with tofu, pork and a side of steamed rice.",
    macroCategory: "food",
    category: "Soup",
    price: 16.9,
    prepTime: "12 min",
    mostOrdered: true,
  },
  {
    id: "4",
    title: "Doenjang Soup",
    description: "Soybean broth with vegetables, tofu and mushrooms.",
    macroCategory: "food",
    category: "Soup",
    price: 14.5,
    prepTime: "10 min",
  },
  {
    id: "5",
    title: "Japchae Noodles",
    description: "Sweet potato noodles tossed with beef and vegetables.",
    macroCategory: "food",
    category: "Noodle",
    price: 15.25,
    prepTime: "9 min",
    promo: true,
  },
  {
    id: "6",
    title: "Spicy Ramyun Bowl",
    description: "Rich spicy broth, soft egg and scallions with premium noodles.",
    macroCategory: "food",
    category: "Noodle",
    price: 13.95,
    prepTime: "6 min",
    mostOrdered: true,
  },
  {
    id: "7",
    title: "Cheese Kimbab Roll",
    description: "Warm rice roll with melted cheese, carrot, spinach and sesame oil.",
    macroCategory: "food",
    category: "Kimbab",
    price: 12.95,
    prepTime: "8 min",
  },
  {
    id: "8",
    title: "Seafood Tofu Soup",
    description: "Light spicy broth with tofu, clams, shrimp and vegetables.",
    macroCategory: "food",
    category: "Soup",
    price: 17.4,
    prepTime: "13 min",
    promo: true,
  },
  {
    id: "9",
    title: "Cold Bibim Noodles",
    description: "Chilled noodles with cucumber, pear and bright gochujang dressing.",
    macroCategory: "food",
    category: "Noodle",
    price: 14.85,
    prepTime: "7 min",
  },
];
